spring.application.name=discount
server.port=8080
logging.level.reactor.netty=DEBUG
logging.level.io.netty=DEBUG

spring.kafka.bootstrap-servers=localhost:9092

# serialization JSON generique
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Autorise Spring serialiser n importe quel package
spring.kafka.producer.properties.spring.json.trusted.packages=*

server.error.include-message=always