# docker-compose.yml
name: delivery-scheduler

services:
  api:
    build:
      context: .
    image: delivery-scheduler:latest
    container_name: delivery-scheduler
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL: gpt-4o-mini
      SERVER_PORT: 8080
    restart: unless-stopped
