name: delivery-scheduler
version: "3.9"

networks:
  delivery-scheduler_default:
    external: true   # <- réseau créé par "docker compose -p delivery-scheduler up"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - delivery-scheduler_default
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - delivery-scheduler_default
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    restart: unless-stopped
